server:
    port: 8073

spring:
    application:
        name: api-gateway
    zipkin:
        base-url: http://zipkin:9411
    cloud:
        gateway:
            routes:
                - id: customer
                  uri: lb://CLIENTE
                  predicates:
                      - Path=/api/v1/clientes/**

eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka
        fetch-registry: true
        register-with-eureka: true